# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# 开启 ZMK Studio 支持以进行可视化改键
CONFIG_ZMK_STUDIO=y

# 启用 Sofle OLED 屏幕显示
CONFIG_ZMK_DISPLAY=y

# 启用 EC11 旋转编码器（旋钮）支持
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment this line below to add rgb underglow / backlight support
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# 开启深度休眠支持（极其重要：如果您没有物理开关，请务必开启此项以省电）
CONFIG_ZMK_SLEEP=y
# 深度休眠触发时间：毫秒（900000 毫秒 = 15 分钟）
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
